### PR TITLE
feat: try parsing value of cell, to set types

### PR DESCRIPTION
**Pull request by GreeFine**
In order to have the types for the values that aren't string, I add a parsing for f64.

### CODE REVIEW

**Comment by GreeFine** [comment]
Maybe this also need a flag to disable it, as it impacts the performance a bit.

I don't think it mandatory because the impact is very small in my tests, but it could still be a nice to have

**Comment by jacobsvante** [comment]
This should definitively be a setting. It's very inexplicit at the moment. I would recommend going with the approach that you can explicitly specify type per column (referenced by index or column header title).

**Comment by GreeFine** [comment]
> This should definitively be a setting. It's very inexplicit at the moment. I would recommend going with the approach that you can explicitly specify type per column (referenced by index or column header title).

I completely agree, but Excel does this by default, for example take this CSV:
```csv
header1;header2;header3
value_str;100;10,0
```
When imported in excel this is what we get:
image
As you can see 100 and 10,0 are treated an imported as numbers

I think what you proposed "explicitly specify type per column" would be nice but is very cumbersome
Maybe we can compromise and keep this functionality behind a `--auto-types` flag ?

PS:
Imports are also dependent on the internationalization, for example I am in france, and here the floats "points" is represented by the "." char.
But I think we do not need to handle this for now.

**Comment by jacobsvante** [comment]
@GreeFine I just released [0.3.0](https://crates.io/crates/csv2xlsx/0.3.0).

With this new version you can specify `-e 1=number -e 2=number` for above example to get columns `header2` and `header3` to be converted to number. (uses zero based indexes).

**Pull request closed without merging**
